databases:
  - name: rfp-db
    databaseName: rfp
    user: admin
  #  plan: free  # Only here, if needed; try omitting to test

services:
  - type: web
    name: risk-opportunities-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --timeout 30 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rfp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rfp-cache
          property: connectionString

  - type: web
    name: risk-opportunities-frontend
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: redis
    name: rfp-cache
    ipAllowList: []
